export const REGISTER_UPDATE_USERNAME = "REGISTER_UPDATE_USERNAME";
export const REGISTER_UPDATE_PASSWORD = "REGISTER_UPDATE_PASSWORD";
export const REGISTER_UPDATE_USERNAME_ERROR = "REGISTER_UPDATE_USERNAME_ERROR";
export const REGISTER_UPDATE_PASSWORD_ERROR = "REGISTER_UPDATE_PASSWORD_ERROR";
