//Register
export const REGISTER_UPDATE_USERNAME = "REGISTER_UPDATE_USERNAME";
export const REGISTER_UPDATE_PASSWORD = "REGISTER_UPDATE_PASSWORD";
export const REGISTER_UPDATE_USERNAME_ERROR = "REGISTER_UPDATE_USERNAME_ERROR";
export const REGISTER_UPDATE_PASSWORD_ERROR = "REGISTER_UPDATE_PASSWORD_ERROR";

//login/Logout
export const SAVE_CURRENT_USER = "SAVE_CURRENT_USER";
export const LOGOUT_CURRENT_USER = "LOGOUT_CURRENT_USER";
export const LOGIN_UPDATE_USERNAME = "LOGIN_UPDATE_USERNAME";
export const LOGIN_UPDATE_PASSWORD = "LOGIN_UPDATE_PASSWORD";
export const LOGIN_UPDATE_USERNAME_ERROR = "LOGIN_UPDATE_USERNAME_ERROR";
export const LOGIN_UPDATE_PASSWORD_ERROR = "LOGIN_UPDATE_PASSWORD_ERROR";

//Movies
export const FETCH_MOVIES = "FETCH_MOVIES";
export const UPDATE_MOVIES_SEARCH_KEYWORDS = "GET_MOVIES_SEARCH_KEYWORDS";
